# Generated by Django 2.0 on 2019-10-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom de catégorie')),
            ],
            options={
                'verbose_name': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nom du produit')),
                ('description', models.TextField(null=True)),
                ('grade', models.CharField(max_length=10, unique=True, verbose_name='Note')),
                ('url', models.CharField(max_length=150, unique=True, verbose_name='URL sur OpenFoodFact')),
                ('url_img', models.CharField(max_length=150, unique=True, verbose_name='URL image')),
                ('slug', models.SlugField(max_length=100)),
                ('categories', models.ManyToManyField(related_name='categories', to='website.Category')),
            ],
            options={
                'verbose_name': 'Produits',
            },
        ),
    ]
