# Generated by Django 2.0 on 2019-10-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191029_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='grade',
            field=models.CharField(max_length=10, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=150, null=True, verbose_name='URL sur OpenFoodFact'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_img',
            field=models.CharField(max_length=150, null=True, verbose_name='URL image'),
        ),
    ]
