# Generated by Django 2.0 on 2019-11-07 10:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0004_auto_20191030_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fav',
            field=models.ManyToManyField(related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
