# Generated by Django 2.0 on 2019-11-07 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_product_fav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fav',
            field=models.ManyToManyField(null=True, related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
