# Generated by Django 2.0 on 2019-11-11 13:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20191107_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fav',
            field=models.ManyToManyField(related_name='fav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_prod',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=255, null=True, verbose_name='URL sur OpenFoodFact'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_img',
            field=models.CharField(max_length=255, null=True, verbose_name='URL image'),
        ),
    ]
